if(NOT DEFINED USE_SUPERLUMINAL)
    option(USE_SUPERLUMINAL "Enable Superluminal" ON)
endif()


set(SUPERLUMINAL_INCLUDE "${CRYENGINE_DIR}/Code/CryPlugins/CrySuperluminal/Include/Empty")
if(USE_SUPERLUMINAL)
if(MSVC_VERSION EQUAL 1900)
    if(WIN64)
        set(SUPERLUMINAL_INCLUDE "${SDK_DIR}/Superluminal/VS2015/x64")
        find_library(SUPERLUMINAL PerformanceAPI PATHS ${SUPERLUMINAL_INCLUDE} )
    elseif(WIN32)
        set(SUPERLUMINAL_INCLUDE "${SDK_DIR}/Superluminal/VS2015/x32")
        find_library(SUPERLUMINAL PerformanceAPI PATHS ${SUPERLUMINAL_INCLUDE} )
    endif()
elseif(MSVC_VERSION GREATER 1900)
    if(WIN64)
        set(SUPERLUMINAL_INCLUDE "${SDK_DIR}/Superluminal/VS2017/x64")
        find_library(SUPERLUMINAL PerformanceAPI PATHS ${SUPERLUMINAL_INCLUDE} )
    elseif(WIN32)
        set(SUPERLUMINAL_INCLUDE "${SDK_DIR}/Superluminal/VS2017/x32")
        find_library(SUPERLUMINAL PerformanceAPI PATHS ${SUPERLUMINAL_INCLUDE} )
    endif()
endif()
Message("Linking superluminal ${SUPERLUMINAL}")
target_link_libraries(${THIS_PROJECT} PRIVATE ${SUPERLUMINAL})
endif()

Message("Including superluminal header from ${SUPERLUMINAL_INCLUDE}")
target_include_directories( ${THIS_PROJECT} PRIVATE ${SUPERLUMINAL_INCLUDE})

